### ISSUE TITLE
Make project portable

### ISSUE THREAD

**Issue by ivankravets** [CalcVox/calcvox#1]
Hi there,

Thanks for using PlatformIO! 🙏 

A few tips to improve project portability:

1. Please remove all GIT sub-modules from `lib` folder
2. Update the `platformio.ini` with:

```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wrover-kit]
platform = espressif32 @ ^6
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters =
    esp32_exception_decoder
    time
build_flags =
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
board_build.partitions = huge_app.csv
lib_deps =
    https://github.com/Chris--A/Keypad.git
    https://github.com/greiman/SdFat.git
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-espeak-ng.git
    https://github.com/pschatzmann/arduino-posix-fs.git
    https://github.com/pschatzmann/arduino-libhelix.git
    https://github.com/codeplea/tinyexpr.git

```

Now, anyone can download the project as ZIP archive and build it.

**Comment by trypsynth** [comment]
Hi Ivan,
Thanks so much for this! I've gone ahead and done as you suggested, and it all works! That's extremely elegant, and should make life a lot easier in the future.
Thanks again!

**Comment by ivankravets** [comment]
Thanks! Could you also add `.pio` to `.gitignore`? This is a dynamic folder and is not required for the project reproducibility.

**Comment by trypsynth** [comment]
It would appear to already be in there. The gitignore has both .pio/ and .pio/build/project.checksum, although the latter seems redundant.

**Comment by trypsynth** [comment]
Ah, got it. Needed to git rm the tiny bit that got committed before the gitignore.
