### ISSUE TITLE
Add equation history

### ISSUE THREAD

**Issue by gyoder** [CalcVox/calcvox#3]
Add a way to navigate history and pull historical equations and evaluations

**Comment by gyoder** [comment]
Needs to reset position when interting

**Comment by trypsynth** [comment]
position now resets when pressing enter. A bit more hardware testing is needed for this, but it's pretty close now!

**Comment by trypsynth** [comment]
Hardware testing complete, this is now good enough for presentations! There's a slightly weird issue with inserting the equation, but it's rare and can be fixed post presentations.
