### ISSUE TITLE
Repeat key needs to have better functionality for repeating the correct equation 

### ISSUE THREAD

**Issue by gyoder** [CalcVox/calcvox#7]
Currently just directly speaks equations but needs more logic

**Comment by trypsynth** [comment]
I think an actually good use of this key is to say the last spoken string again. Thoughts?

**Comment by gyoder** [comment]
I think that should be fine. We should add a key that says what's in the current equation

**Comment by trypsynth** [comment]
I believe this fully works now. We need to test it on the hardware, but I'll close this, reopening if it breaks.
